addons:
  apt:
    packages:
      - graphviz

services:
  - docker
    
before_script:
  - curl -L http://phpdoc.org/phpDocumentor.phar --output ./phpdoc.phar

script: php ./phpdoc.phar -d ./src -t ./docs

deploy:
- provider: pages
  github-token: $GITHUB_TOKEN
  local-dir: "./docs/"
  skip-cleanup: true
  on:
    branch: master

jobs:
  include:
    - stage: build docker image
      script: bash ./build.sh